var jokes = [
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What do you call a fake noodle? An impasta!",
    "Why don't oysters give to charity? Because they're shellfish!",
    "Why did the math book look sad? Because it had too many problems!",
    "Why Dasha is so much preety? Because Dasha have so pretty and lovely husband.",
    "Why did the coffee file a police report? It got mugged!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the frog call his insurance company? He had a jump in his car!",
    "Why can't you hear a pterodactyl in the bathroom? Because the pee is silent!",
    "Why did the cookie go to the doctor? Because it was feeling crumbly!",
    "Why did the farmer win an award? Because he was out standing in his field!",
    "Why did the skeleton go to the party alone? He had nobody to dance with!",
    "Why did the banana go to the doctor? Because it wasn't peeling well!",
    "Why did the police arrest the turkey? They suspected it of fowl play!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the whale cross the ocean? To get to the other tide!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the octopus beat the shark in a fight? Because it was well-armed!",
    "Why don't lobsters share? Because they're shellfish!",
    "Why did the snail go to the car dealership? He wanted to buy a new shell!",
    "Why did the bicycle fall over? It was two-tired!",
    "Why did the cookie go to the doctor? It was feeling crummy!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the coffee file a police report? It got mugged!",
    "Why don't ghosts go to the beach? They don't like the sand in their BOOts!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the farmer win an award? Because he was out standing in his field!",
    "Why did the frog call his insurance company? He had a jump in his car!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the math book look sad? Because it had too many problems!",
    "Why did the banana go to the doctor? Because it wasn't peeling well!",
    "Why did the police arrest the turkey? They suspected it of fowl play!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "Why do we tell actors to 'break a leg?' Because every play has a cast.",
    "Why couldn't the bicycle stand up by itself? Because it was two-tired.",
    "Why Sike fart? Because Sike don't go in toilet.",
    "Why Aklesh don't study Because Aklesh thinks i know everything.",
    "Why Jay Ram change his name to Alex? Because Jay Ram is not cool name.",
    "Why Rishi thnik it's cool? Because Rishi real name is Nandan."
];  
